Moved upstream merge of 3.4-tar to backups and recovered original tarball with unit test scripts

diff --git a/docker/mongodb/3.4-tar/root/usr/bin/run-mongod b/docker/mongodb/3.4-tar/root/usr/bin/run-mongod
--- a/docker/mongodb/3.4-tar/root/usr/bin/run-mongod
+++ b/docker/mongodb/3.4-tar/root/usr/bin/run-mongod
@@ -1,70 +1,82 @@
 #!/bin/bash
+#
+# Run mongod in a StatefulSet-based replica set. See
+# https://github.com/sclorg/mongodb-container/blob/master/examples/petset/README.md
+# for a description of how this is intended to work.
+#
+# Note:
+# - It does not attempt to remove the host from the replica set configuration
+#   when it is terminating. That is by design, because, in a StatefulSet, when a
+#   pod/container terminates and is restarted by OpenShift, it will always have
+#   the same hostname. Removing hosts from the configuration affects replica set
+#   elections and can impact the replica set stability.
 
 set -o errexit
 set -o nounset
 set -o pipefail
 
-# shellcheck source=/dev/null
-source ${CONTAINER_SCRIPTS_PATH:-}/generate_container_user
+# Concatenate shared files
+share_files=( $( find "${CONTAINER_SCRIPTS_PATH}" -type f -name '*.sh' -not -path "*${CONTAINER_SCRIPTS_PATH}/test-functions.sh" ) )
 
-# shellcheck source=/dev/null
-source ${CONTAINER_SCRIPTS_PATH:-}/common.sh
-
-# shellcheck source=/dev/null
-source ${CONTAINER_SCRIPTS_PATH:-}/init-mongod
-
-# shellcheck source=/dev/null
-source ${CONTAINER_SCRIPTS_PATH:-}/init-replset
+# Load libraries into current shell
+for share_file in "${share_files[@]}"; do
+	source "${share_file}"
+done
 
 unset share_files share_file
-trap cleanup SIGINT SIGTERM
 
-log_info "Checking env variables"
-if [[ -n "${MONGODB_REPLICA_NAME:-}" ]]; then
+function cleanup() {
+	if [[ -n "${MONGODB_REPLICA_NAME-}" ]]; then
+		mongo_remove
+	fi
+
+	echo "=> Shutting down MongoDB server ..."
+	pkill -INT mongod || :
+	wait_for_mongo_down
+	exit 0
+}
+
+trap 'cleanup' SIGINT SIGTERM
+
+if [[ -n "${MONGODB_REPLICA_NAME-}" ]]; then
 	REPLICATION=1	check_env_vars
 else
 	check_env_vars
 fi
 
-log_info "Checking data directory"
-check_data_dir
+setup_wiredtiger_cache ${CONTAINER_SCRIPTS_PATH}/mongodb.conf.template
 
-log_info "Setting up storage cache"
-setup_wiredtiger_cache "${CONTAINER_SCRIPTS_PATH:-}/mongodb.conf.template"
-
-log_info "Setting up config file"
-if [[ ! -s "$MONGODB_CONFIG_PATH" ]]; then
-	envsubst < "${CONTAINER_SCRIPTS_PATH:-}/mongodb.conf.template" > "$MONGODB_CONFIG_PATH"
+# If user provides own config file use it and do not generate new one
+if [[ ! -s "${MONGODB_CONFIG_PATH}" ]]; then
+	# Generate config file for MongoDB
+	envsubst < "${CONTAINER_SCRIPTS_PATH}/mongodb.conf.template" > "${MONGODB_CONFIG_PATH}"
 fi
 
-# [TODO] Capture exit code and print error if initialization failed.
-if [[ -n "${MONGODB_REPLICA_NAME:-}" ]]; then
+mongo_common_args="-f $MONGODB_CONFIG_PATH"
+setup_default_datadir
+
+if [[ -n "${MONGODB_REPLICA_NAME-}" ]]; then
+	# Cache for cleanup
+	cache_container_addr
+
+	# [NOTE] May modify MONGODB_CONFIG_PATH
 	setup_keyfile
 
+	# [TODO] Capture exit code of `replicaset` and exit with an error if the
+	# initialization failed, so that the container will be restarted and the
+	# user can gain more visibility that there is a problem in a way other than
+	# just inspecting log messages.
 	replicaset &
 
+	# Run `mongod` in a subshell because MONGODB_ADMIN_PASSWORD should still be
+	# defined when the trapped call to `cleanup` references it.
 	(
-	unset_env_vars
+	# Make sure env variables don't propagate to mongod process.
+	unset MONGODB_USER MONGODB_PASSWORD MONGODB_DATABASE MONGODB_ADMIN_PASSWORD
 
-	log_info "Starting mongo daemon (replica set)"
-	$MONGOD --config "$MONGODB_CONFIG_PATH" --keyFile $MONGODB_KEYFILE_PATH --replSet "${MONGODB_REPLICA_NAME:-}"
+	mongod $mongo_common_args --replSet "${MONGODB_REPLICA_NAME}"
 	) &
 	wait
 else
-	standalone "$MONGODB_CONFIG_PATH" &
-
-	(
-	log_info "Starting mongo daemon (standalone)"
-	$MONGOD --config "$MONGODB_CONFIG_PATH"
-	) &
-	wait
-
-	unset_env_vars
-
-	log_info "Stopping mongo daemon"
-	$MONGOD --config "$MONGODB_CONFIG_PATH" --shutdown
-	wait_for_mongo_down
-
-	log_info "Starting mongo daemon (enable access control)"
-	$MONGOD --config "$MONGODB_CONFIG_PATH" --auth
+	standalone
 fi
